//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lua.Models
{
    using System;
    using System.ComponentModel;

    public partial class Capitulo
    {
        public int Id { get; set; }
        public string UsuarioId { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> SeccionId { get; set; }

        [DisplayName("Contenido")]
        public string ContenidoHTML { get; set; }
        public byte Posicion { get; set; }
        public string Portada { get; set; }
        public bool Activo { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
